package cgeo.geocaching.calculator;

import org.json.JSONException;
import org.junit.Test;
import static org.assertj.core.api.Java6Assertions.assertThat;

public class CalculatedCoordinateMigratorTest {

    private static final String JSON_SAMPLE_1 = "{\"format\":2,\"plainLat\":\"N 53° 33.065'\",\"plainLon\":\"E 009° 59.621'\",\"latHemisphere\":78,\"lonHemisphere\":69,\"buttons\":[{\"type\":0,\"inputVal\":53,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":51,\"autoChar\":45,\"customChar\":0},{\"type\":1,\"inputVal\":51,\"autoChar\":65,\"customChar\":0},{\"type\":0,\"inputVal\":51,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":48,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":54,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":53,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":48,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":48,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":57,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":53,\"autoChar\":66,\"customChar\":0},{\"type\":1,\"inputVal\":57,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":67,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":67,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":67,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":67,\"customChar\":0},{\"type\":0,\"inputVal\":54,\"autoChar\":67,\"customChar\":0},{\"type\":2,\"inputVal\":50,\"autoChar\":67,\"customChar\":0},{\"type\":0,\"inputVal\":49,\"autoChar\":67,\"customChar\":0}],\"equations\":[{\"name\":65,\"expression\":\"a+b\"},{\"name\":66,\"expression\":\"5\"}],\"freeVariables\":[{\"name\":97,\"expression\":\"3\"},{\"name\":98,\"expression\":\"4\"}]}";
    private static final String JSON_SAMPLE_2 = "{\"format\":0,\"plainLat\":\"N 53° 33.06A'\",\"plainLon\":\"E 009° 59.B21'\",\"latHemisphere\":78,\"lonHemisphere\":69,\"buttons\":[{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0}],\"equations\":[{\"name\":65,\"expression\":\"a+b\"},{\"name\":66,\"expression\":\"5\"}],\"freeVariables\":[{\"name\":97,\"expression\":\"3\"},{\"name\":98,\"expression\":\"4\"}]}";
    private static final String JSON_SAMPLE_3 = "{\"format\":2,\"plainLat\":\"N 53° 32.555'\",\"plainLon\":\"E 009° 59.333'\",\"latHemisphere\":78,\"lonHemisphere\":69,\"buttons\":[{\"type\":0,\"inputVal\":53,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":51,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":51,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":50,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":53,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":53,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":53,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":48,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":48,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":57,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":53,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":57,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":0,\"inputVal\":0,\"autoChar\":45,\"customChar\":0},{\"type\":1,\"inputVal\":53,\"autoChar\":65,\"customChar\":0},{\"type\":0,\"inputVal\":51,\"autoChar\":66,\"customChar\":0},{\"type\":0,\"inputVal\":51,\"autoChar\":66,\"customChar\":0}],\"equations\":[{\"name\":65,\"expression\":\"5\"}],\"freeVariables\":[]}";

    @Test
    public void simpleJson() throws JSONException {
        assertThat(CalculatedCoordinateMigrator.createFromJson(JSON_SAMPLE_1).toString()).isEqualTo("");
    }
}
